/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrderInfo { 
    amount?: number;
    date?: Date;
    id?: number;
    status?: OrderInfo.StatusEnum;
}
export namespace OrderInfo {
    export type StatusEnum = 'ACCEPTED' | 'PROCESSING' | 'SHIPPED' | 'CANCELED';
    export const StatusEnum = {
        ACCEPTED: 'ACCEPTED' as StatusEnum,
        PROCESSING: 'PROCESSING' as StatusEnum,
        SHIPPED: 'SHIPPED' as StatusEnum,
        CANCELED: 'CANCELED' as StatusEnum
    };
}
